// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
)

type Bill struct {
	ID     int32         `json:"id"`
	UserID sql.NullInt32 `json:"user_id"`
	Money  int32         `json:"money"`
}

type User struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Money int32  `json:"money"`
}
